Add defstatus

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -77,6 +77,9 @@ jobs:
         pip install -e .[test]
     - name: Test with nosetests
       run: |
+        ls -l /usr/bin/start_ecflow.sh || echo "/usr/bin/start_ecflow.sh not found"
+        ls -l /usr/sbin/ecflow_start || echo "/usr/sbin/ecflow_start not found"
+        ls -l /usr/lib/python3/dist-packages/ecflow
         export PATH=$PWD/test/bin:/usr/bin/:$PATH && CLIENTID=${{ secrets.CLIENTID }} nosetests
     - name: Coveralls
       if: ${{ matrix.python-version == 3.6 }}
